---
# tasks/main.yml

- name: Copy issue file
  copy:
    src: issue
    dest: /etc/issue
    owner: root
    group: root
    mode: '0644'
    backup: yes  # Added to back up the existing /etc/issue before overwriting

- name: Copy issue.net file
  copy:
    src: issue.net
    dest: /etc/issue.net
    owner: root
    group: root
    mode: '0644'
    backup: yes  # Added to back up the existing /etc/issue.net before overwriting

- name: Copy ssh_banner file
  copy:
    src: ssh_banner
    dest: /etc/ssh/ssh_banner
    owner: root
    group: root
    mode: '0644'

- name: Copy access.conf file
  copy:
    src: access.conf
    dest: /etc/security/access.conf
    owner: root
    group: root
    mode: '0440'

- name: Copy aapuser sudoers file
  copy:
    src: 10-aapuser
    dest: /etc/sudoers.d/10-aapuser
    owner: root
    group: root
    mode: '0440'


- name: Delete specific SSH config files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/ssh/sshd_config.d/50-cloud-init.conf
    - /etc/ssh/sshd_config.d/50-cloudimg-settings.conf
    - /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
  ignore_errors: yes  # In case the files do not exist
  
- name: Copy sshd file
  copy:
    src: sshd
    dest: /etc/pam.d/sshd
    owner: root
    group: root
    mode: '0644'
    backup: yes  # Already present: Backs up the existing sshd_config before overwriting
  register: sshd_config_copy

- name: Copy sshd_config file
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
    backup: yes  # Already present: Backs up the existing sshd_config before overwriting
  register: sshd_config_copy

- name: Restart ssh service
  service:
    name: ssh
    state: restarted
  when: sshd_config_copy.changed and ansible_distribution in ['Ubuntu', 'Debian']  # Adjust based on your distros

- name: Restart ssh service
  service:
    name: sshd
    state: restarted
  when: sshd_config_copy.changed and ansible_distribution in ['RedHat']  # Adjust based on your distros