---
# tasks/main.yml

- name: Copy issue file
  copy:
    src: issue
    dest: /etc/issue
    owner: root
    group: root
    mode: '0644'
    backup: yes  # Added to back up the existing /etc/issue before overwriting

- name: Copy issue.net file
  copy:
    src: issue.net
    dest: /etc/issue.net
    owner: root
    group: root
    mode: '0644'
    backup: yes  # Added to back up the existing /etc/issue.net before overwriting

- name: Copy ssh_banner file
  copy:
    src: ssh_banner
    dest: /etc/ssh/ssh_banner
    owner: root
    group: root
    mode: '0644'

- name: Copy sshd_config file
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
    backup: yes  # Already present: Backs up the existing sshd_config before overwriting

- name: Restart ssh service
  service:
    name: ssh
    state: restarted
  when: ansible_distribution in ['Ubuntu', 'Debian']  # Adjust based on your distros