---
- name: Ensure libpam-modules is installed (contains pam_faillock)
  apt:
    name: libpam-modules
    state: present
    update_cache: yes

- name: Backup existing /etc/pam.d/common-auth
  copy:
    src: /etc/pam.d/common-auth
    dest: /etc/pam.d/common-auth.bak
    remote_src: yes
    backup: yes

- name: Set custom PAM configuration for faillock in /etc/pam.d/common-auth
  copy:
    src: common-auth
    dest: /etc/pam.d/common-auth
    owner: root
    group: root
    mode: '0644'

- name: Backup existing /etc/pam.d/common-account
  copy:
    src: /etc/pam.d/common-account
    dest: /etc/pam.d/common-account.bak
    remote_src: yes
    backup: yes

- name: Set custom PAM configuration for faillock in /etc/pam.d/common-account
  copy:
    src: common-account
    dest: /etc/pam.d/common-account
    owner: root
    group: root
    mode: '0644'

- name: Backup existing /etc/security/faillock.conf
  copy:
    src: /etc/security/faillock.conf
    dest: /etc/security/faillock.conf.bak
    remote_src: yes
    backup: yes

- name: Set custom PAM configuration for faillock in /etc/security/faillock.conf
  copy:
    src: faillock.conf
    dest: /etc/security/faillock.conf
    owner: root
    group: root
    mode: '0644'
