---

- name: Install required packages
  package:
    name: "{{ authselect_packages }}"
    state: present

- name: Manage user-nsswitch.conf
  template:
    src: "{{ item }}"
    dest: "{{ __authselect_user_nsswitch_conf_file }}"
    mode: 0644
    owner: root
    group: root
  with_first_found:
    - files:
      - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}-user-nsswitch.conf.j2"
      - "base-user-nsswitch.conf.j2"
  notify:
    - Update PAM with authselect

- name: Get current authselect config
  command: authselect current -r
  register: authselect_current_raw
  check_mode: no
  changed_when: false
  failed_when:
    - authselect_current_raw.rc != 0
    - '"No existing configuration detected" not in authselect_current_raw.stdout'

- name: Set fact authselect_force true if no existing configuration detected.
  set_fact:
    authselect_force: true
  when:
    - '"No existing configuration detected" in authselect_current_raw.stdout'

- name: Verify current authselect profile and features are in the desired state
  set_fact:
    authselect_current_profile: "{{ authselect_current_raw.stdout.split()[0] }}"
    authselect_current_features: "{{ authselect_current_raw.stdout.split()[1:] }}"
  changed_when:
    - authselect_profile != authselect_current_profile or
      authselect_features | sort != authselect_current_features | sort or
      authselect_current_raw.failed
  notify:
    - Update PAM with authselect

...
