---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: authselect-centos-8
    image: docker.io/centos:8
    pre_build_image: true
  - name: authselect-fedora-30
    image: docker.io/fedora:30
    pre_build_image: true
  - name: authselect-fedora-31
    image: docker.io/fedora:31
    pre_build_image: true
  - name: authselect-fedora-32
    image: docker.io/fedora:32
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: ansible-lint .
