galaxy_info:
  author: smlloyd
  role_name: authselect
  description: Configure pam with authselect
  license: "Beerware License"
  min_ansible_version: 2.7
  platforms:
    - name: EL
      versions:
        - 8
        - 9
    - name: Fedora
      versions:
        - 30
        - 31
        - 32
  galaxy_tags: []
dependencies: []
