collections:
- name: ansible.windows
- name: community.windows
- name: community.general
- name: azure.azcollection
- name: amazon.aws
- name: community.aws
- name: google.cloud
- name: ansible.posix
- name: community.crypto
- name: community.hashi_vault
- name: kubernetes.core
- name: ansible.utils
- name: community.docker
