---
# Ensure system is attached to Ubuntu Pro
- name: Attach to Ubuntu Pro
  ansible.builtin.command: "pro attach {{ lookup('env', 'UBUNTU_PRO_TOKEN') }}"
  register: result
  failed_when: result.rc not in [0, 2]
  tags: [ubuntu_pro]

# Ensure landscape-client is installed
- name: Ensure landscape-client is installed
  ansible.builtin.apt:
    name: landscape-client
    state: present
    update_cache: yes
  tags: [landscape]

# Deploy Landscape config file
- name: Deploy Landscape config file
  ansible.builtin.copy:
    src: client.conf
    dest: /etc/landscape/client.conf
    owner: root
    group: root
    mode: '0644'
  tags: [landscape]

# Ensure landscape-client service is enabled and running
- name: Ensure landscape-client service is enabled and running
  ansible.builtin.service:
    name: landscape-client
    state: started
    enabled: yes
  tags: [landscape]
