---
# Ensure system is attached to Ubuntu Pro
- name: Attach to Ubuntu Pro
  ansible.builtin.command: "pro attach {{ lookup('env', 'UBUNTU_PRO_TOKEN') }}"
  register: result
  failed_when: result.rc not in [0, 2]
  tags: [ubuntu_pro]

# Ensure landscape-client is installed
- name: Ensure landscape-client is installed
  ansible.builtin.apt:
    name: landscape-client
    state: present
    update_cache: yes
  tags: [landscape]

# Deploy Landscape config file
# Configure Landscape client dynamically
- name: Configure landscape-client dynamically
  ansible.builtin.command: >
    landscape-config
    --silent
    --account-name "{{ lookup('env','LANDSCAPE_ACCOUNT_NAME') }}"
    --url=https://landscape.canonical.com/message-system
    --ping-url=http://landscape.canonical.com/ping
    --include-manager-plugins=ScriptExecution
    --script-users root
  register: landscape_config_result
  changed_when: landscape_config_result.rc == 0
  tags: [landscape]

# Ensure landscape-client service is enabled and running
- name: Ensure landscape-client service is enabled and running
  ansible.builtin.service:
    name: landscape-client
    state: started
    enabled: yes
  tags: [landscape]
