---
- name: Create Azure VM based on AAP Survey
  hosts: localhost
  connection: local
  gather_facts: false

  # These variables will be populated by the AAP Survey.
  # Default values are provided here for local testing.
  vars:
    survey_resource_group: "rg-aap-managed-vms"
    survey_vm_name: "web-server-01"
    survey_location: "eastus"
    survey_availability_zone: "1" # 'None' or a zone number like '1', '2', '3'
    survey_image: "Ubuntu 22.04-LTS"
    survey_size: "Standard_B1s"
    admin_ssh_key_public: "ssh-rsa AAAA..." # This should be populated from an AAP Credential

    # A map to translate user-friendly image names to Azure-specific details
    image_map:
      "Ubuntu 22.04-LTS":
        publisher: "Canonical"
        offer: "0001-com-ubuntu-server-jammy"
        sku: "22_04-lts-gen2"
        version: "latest"
      "RHEL 9.2":
        publisher: "RedHat"
        offer: "RHEL"
        sku: "9_2"
        version: "latest"
      "Debian 11":
        publisher: "Debian"
        offer: "debian-11"
        sku: "11-gen2"
        version: "latest"

  tasks:
    - name: Ensure Resource Group exists
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ survey_resource_group }}"
        location: "{{ survey_location }}"
      register: rg

    - name: Create Virtual Network
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "{{ survey_resource_group }}"
        name: "vnet-{{ survey_vm_name }}"
        address_prefixes: "10.1.0.0/16"

    - name: Add a subnet
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ survey_resource_group }}"
        name: "subnet-{{ survey_vm_name }}"
        address_prefix: "10.1.1.0/24"
        virtual_network: "vnet-{{ survey_vm_name }}"

    - name: Create Public IP address
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: "{{ survey_resource_group }}"
        name: "pip-{{ survey_vm_name }}"
        allocation_method: Static
        sku: Standard # Standard SKU is required for zones
      register: public_ip

    - name: Create Network Security Group (NSG) and allow SSH
      azure.azcollection.azure_rm_securitygroup:
        resource_group: "{{ survey_resource_group }}"
        name: "nsg-{{ survey_vm_name }}"
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
      register: nsg

    - name: Create Network Interface Card (NIC)
      azure.azcollection.azure_rm_networkinterface:
        resource_group: "{{ survey_resource_group }}"
        name: "nic-{{ survey_vm_name }}"
        # VNet/Subnet must be top-level in your version
        virtual_network: "vnet-{{ survey_vm_name }}"     # alias: virtual_network_name
        subnet_name: "subnet-{{ survey_vm_name }}"       # alias: subnet
        # NSG can be name or full resource ID
        security_group: "{{ nsg.state.id | default('nsg-' ~ survey_vm_name) }}"
        ip_configurations:
          - name: ipconfig1
            # Pick ONE of the following depending on how you want to reference the PIP:
            # If PIP is in same RG, using name is fine:
            public_ip_address_name: "pip-{{ survey_vm_name }}"   # aliases: public_ip_name
            # OR use the resource ID for cross-RG robustness:
            # public_ip_address: "{{ public_ip.state.id }}"
            primary: true
      register: nic

      - name: Create the Virtual Machine with specified requirements
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ survey_resource_group }}"
        name: "{{ survey_vm_name }}"
        vm_size: "{{ survey_size }}"

        # Availability zones: module expects a list (strings). Your Jinja expression is fine.
        zones: "{{ [survey_availability_zone] if survey_availability_zone not in ['None', ''] else omit }}"

        # --- Identity ---
        vm_identity:
          type: SystemAssigned

        # --- OS & Access (Linux) ---
        os_type: Linux
        admin_username: "aapuser"

        # SSH key goes here at top level (not under os_profile)
        ssh_public_keys:
          - path: "/home/aapuser/.ssh/authorized_keys"
            key_data: "{{ admin_ssh_key_public }}"

        # Linux-specific options, including Azure-orchestrated patching
        linux_config:
          disable_password_authentication: true
          patch_settings:
            patch_mode: AutomaticByPlatform
            assessment_mode: AutomaticByPlatform

        # --- Networking ---
        # Your previous NIC register is `nic`. The VM module expects names as a list.
        network_interface_names:
          - "{{ nic.state.name | default('nic-' ~ survey_vm_name) }}"

        # --- Image ---
        # Your image_map[survey_image] should be a dict with publisher/offer/sku/version or an image reference object.
        image: "{{ image_map[survey_image] }}"

        # Optional disk defaults; adjust if you have different requirements
        managed_disk_type: StandardSSD_LRS
        os_disk_size_gb: 64
        os_disk_caching: ReadWrite
        
        state: present
      register: vm_result

    - name: Enable Entra ID (formerly Azure AD) login for the VM
      # This extension enables SSH login using Entra ID credentials
      azure.azcollection.azure_rm_virtualmachineextension:
        name: "AADSSHLoginForLinux"
        resource_group: "{{ survey_resource_group }}"
        virtual_machine_name: "{{ survey_vm_name }}"
        publisher: "Microsoft.Azure.ActiveDirectory"
        virtual_machine_extension_type: "AADSSHLoginForLinux"
        type_handler_version: "1.0"
        auto_upgrade_minor_version: true
        state: present

    - name: Display VM information
      ansible.builtin.debug:
        msg:
          - "VM '{{ survey_vm_name }}' has been created successfully."
          - "Resource Group: {{ survey_resource_group }}"
          - "Public IP Address: {{ public_ip.state.ip_address }}"
          - "To connect via SSH as the local admin: ssh aapuser@{{ public_ip.state.ip_address }}"
          - "Entra ID login and System-Assigned Managed Identity are enabled."
          - "Guest OS patching is set to AutomaticByPlatform."