---
- name: Configure pam_faillock on Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Insert pam_faillock preauth rule
      community.general.pamd:
        name: common-auth
        type: auth
        control: required
        module_path: pam_faillock.so
        module_arguments:
          - preauth
          - silent
          - deny=5
          - unlock_time=900
        state: before
        new_type: auth
        new_control: '[success=1 default=ignore]'
        new_module_path: pam_unix.so

    - name: Insert pam_faillock authfail rule
      community.general.pamd:
        name: common-auth
        type: auth
        control: '[default=die]'
        module_path: pam_faillock.so
        module_arguments:
          - authfail
          - deny=5
          - unlock_time=900
        state: after
        new_type: auth
        new_control: requisite
        new_module_path: pam_deny.so

    - name: Insert pam_faillock authsucc rule
      community.general.pamd:
        name: common-auth
        type: auth
        control: sufficient
        module_path: pam_faillock.so
        module_arguments:
          - authsucc
          - deny=5
          - unlock_time=900
        state: after
        new_type: auth
        new_control: required
        new_module_path: pam_permit.so
