---
- name: Configure baseline policy on Ubuntu with PAM Authentication and SSSD
  hosts: all
  become: true
  roles:
    - password_sssd
    - session_timeout
    - ssh_banner
    - tls_ciphers
    - elastic_agent

# Only run these roles/tasks on Ubuntu systems
    - role: landscape_setup
      when: ansible_distribution == 'Ubuntu'