---
- name: Configure baseline policy on Ubuntu/Debian servers with PAM Authentication and Azure Active Directory (Entra ID)
  hosts: all
  become: true
  gather_facts: true

  vars:
    aadssh_extension_name: "AADSSHLoginForLinux"
    aadssh_publisher: "Microsoft.Azure.ActiveDirectory.AADSSHLoginForLinux"
    aadssh_extension_version: "1.0"
    azure_access_token: "{{ lookup('env', 'AZURE_ACCESS_TOKEN') }}"
    azure_subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
    azure_resource_group: "{{ lookup('env', 'AZURE_RESOURCE_GROUP') }}"
    azure_location: "{{ lookup('env', 'AZURE_LOCATION') | default(azure_region) }}"

  tasks:
    - name: Include baseline roles for Ubuntu/Debian
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - AADSSHLogin
        - password_aad
        - session_timeout
        - ssh_banner
        - tls_ciphers
        - elastic_agent
      when: ansible_distribution in ['Ubuntu', 'Debian']

    - name: Include landscape setup role (Ubuntu only)
      ansible.builtin.include_role:
        name: landscape_setup
      when: ansible_distribution == 'Ubuntu'