---

authselect_packages:
  - authselect
  - sssd

authselect_user_nsswitch_conf_defaults:
  passwd: sss files systemd
  shadow: files
  group: sss files systemd
  hosts: files dns myhostname
  services: files sss
  netgroup: sss
  automount: files sss
  aliases: files
  ethers: files
  gshadow: files
  # initgroups: files
  networks: files dns
  protocols: files
  publickey: files
  rpc: files
  # bootparams: files
  # netmasks: files

authselect_profile: sssd
authselect_features: []
authselect_force: false
