---
- name: Get AAD SSH extension info
  azure.azcollection.azure_rm_virtualmachineextension_info:
    resource_group: "{{ hostvars[inventory_hostname].resource_group }}"
    vm_name: "{{ hostvars[inventory_hostname].name | default(inventory_hostname) }}"
    name: "AADSSHLoginForLinux"
  register: extension_info

- name: Ensure AADSSHLoginForLinux is present
  azure.azcollection.azure_rm_virtualmachineextension:
    resource_group: "{{ hostvars[inventory_hostname].resource_group }}"
    vm_name: "{{ hostvars[inventory_hostname].name | default(inventory_hostname) }}"
    name: "AADSSHLoginForLinux"
    location: "{{ hostvars[inventory_hostname].location }}"
    publisher: "Microsoft.Azure.ActiveDirectory"
    virtual_machine_extension_type: "AADSSHLoginForLinux"
    type_handler_version: "1.0"
    auto_upgrade_minor_version: true
    state: present
  when: (extension_info.extensions | selectattr('name', 'equalto', 'AADSSHLoginForLinux') | list | length) == 0